name: Build_OFDRW_Command_Tool

on:
  workflow_dispatch: 

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'

      - name: Build Tool with Dependencies
        # 这一步进入 tool 模块，并打出一个包含所有依赖的 jar (Fat Jar)
        run: |
          mvn clean package -DskipTests -pl ofdrw-tool -am
          
      - name: Collect Result
        run: |
          # 找到那个体积最大的、名字带 with-dependencies 的包
          mkdir output
          cp ofdrw-tool/target/*-with-dependencies.jar output/ofdrw-command.jar

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: OFDRW-Executable-Tool
          path: output/ofdrw-command.jar
